#!/bin/bash
# bump-version.sh — Read version.properties, bump MAJOR/MINOR/BUILD, generate version.js
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_FILE="$PROJECT_DIR/version.properties"
VERSION_JS_FILE="$PROJECT_DIR/www/js/version.js"

# Fallback: also check if version.js belongs somewhere else
if [ ! -f "$VERSION_FILE" ]; then
    # Create version.properties if it doesn't exist
    echo "version.properties not found. Creating default..."
    cat > "$VERSION_FILE" << 'EOF'
MAJOR=1
MINOR=0
BUILD=0
EOF
    echo "Created $VERSION_FILE with MAJOR=1, MINOR=0, BUILD=0"
fi

# Determine which part to bump
PART="${1:-BUILD}"
PART=$(echo "$PART" | tr '[:lower:]' '[:upper:]')

echo "=== bump-version.sh ==="
echo "Bumping: $PART"

# Read current values
source "$VERSION_FILE"
MAJOR="${MAJOR:-1}"
MINOR="${MINOR:-0}"
BUILD="${BUILD:-0}"

echo "Current version: $MAJOR.$MINOR.$BUILD"

# Bump
case "$PART" in
    MAJOR)
        MAJOR=$((MAJOR + 1))
        MINOR=0
        BUILD=0
        ;;
    MINOR)
        MINOR=$((MINOR + 1))
        BUILD=0
        ;;
    BUILD|*)
        BUILD=$((BUILD + 1))
        ;;
esac

echo "New version:     $MAJOR.$MINOR.$BUILD"

# Write back to version.properties
cat > "$VERSION_FILE" << EOF
MAJOR=$MAJOR
MINOR=$MINOR
BUILD=$BUILD
EOF

echo "Updated $VERSION_FILE"

# Generate version.js
VERSION_JS_DIR="$(dirname "$VERSION_JS_FILE")"
mkdir -p "$VERSION_JS_DIR"

APP_VERSION="${MAJOR}.${MINOR}.${BUILD}"

cat > "$VERSION_JS_FILE" << EOF
// Auto-generated by bump-version.sh
// Do not edit manually — run bump-version.sh to update

const APP_VERSION = '${APP_VERSION}';
const APP_VERSION_MAJOR = ${MAJOR};
const APP_VERSION_MINOR = ${MINOR};
const APP_VERSION_BUILD = ${BUILD};
const APP_BUILD_DATE = '$(date -u +%Y-%m-%dT%H:%M:%SZ)';
EOF

echo "Generated $VERSION_JS_FILE"
echo "APP_VERSION = ${APP_VERSION}"
echo "=== bump-version.sh: DONE ==="
